//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paint_Nest_WebApp.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public string product_name { get; set; }
        public string product_size { get; set; }
        public decimal product_price { get; set; }
        public string product_color { get; set; }
        public int quantity { get; set; }
    }
}
