//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paint_Nest_WebApp.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Paints = new HashSet<Paint>();
        }
    
        public int companyID { get; set; }
        public string company_name { get; set; }
        public string company_address { get; set; }
        public string company_address_state { get; set; }
        public string company_address_zipcode { get; set; }
        public string company_address_city { get; set; }
        public string company_address_country { get; set; }
        public string company_contact { get; set; }
        public string company_email { get; set; }
        public string company_password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paint> Paints { get; set; }
    }
}
