//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paint_Nest_WebApp.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRegister
    {
        public string customer_name { get; set; }
        public string customer_email { get; set; }
        public string customer_password { get; set; }
    }
}
