//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paint_Nest_WebApp.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paint()
        {
            this.PaintColors = new HashSet<PaintColor>();
        }
    
        public int paintID { get; set; }
        public string paintCategoryID { get; set; }
        public Nullable<int> companyID { get; set; }
        public string paint_name { get; set; }
        public string paint_description { get; set; }
        public Nullable<int> paint_QtrPrice { get; set; }
        public Nullable<int> paint_GalPrice { get; set; }
        public Nullable<int> paint_DrumPrice { get; set; }
        public string paint_image { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual PaintCategory PaintCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaintColor> PaintColors { get; set; }
    }
}
