//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paint_Nest_WebApp.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaintCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaintCategory()
        {
            this.Paints = new HashSet<Paint>();
        }
    
        public string paintCategoryID { get; set; }
        public string mainCategoryName { get; set; }
        public string mainCategoryDescription { get; set; }
        public string subCategoryName { get; set; }
        public string subCategoryDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paint> Paints { get; set; }
    }
}
