//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paint_Nest_WebApp.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Paint_NestEntities : DbContext
    {
        public Paint_NestEntities()
            : base("name=Paint_NestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<ContactU> ContactUs { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Paint> Paints { get; set; }
        public virtual DbSet<PaintCategory> PaintCategories { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<CustomerRegister> CustomerRegisters { get; set; }
        public virtual DbSet<PaintColor> PaintColors { get; set; }
        public virtual DbSet<Test1> Test1 { get; set; }
    
        public virtual ObjectResult<string> getCustName(string customer_email)
        {
            var customer_emailParameter = customer_email != null ?
                new ObjectParameter("customer_email", customer_email) :
                new ObjectParameter("customer_email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getCustName", customer_emailParameter);
        }
    }
}
